"""add_payfast_subscription_fields

Revision ID: 0b3fcbf469e3
Revises: f9e708f7c990
Create Date: 2025-11-12 14:59:03.769519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3fcbf469e3'
down_revision = 'f9e708f7c990'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('payfast_subscription_token', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('payfast_subscription_status', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('subscription_next_billing_date', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('payment_method_last_four', sa.String(length=4), nullable=True))
    op.add_column('organizations', sa.Column('payment_failures', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'payment_failures')
    op.drop_column('organizations', 'payment_method_last_four')
    op.drop_column('organizations', 'subscription_next_billing_date')
    op.drop_column('organizations', 'subscription_started_at')
    op.drop_column('organizations', 'payfast_subscription_status')
    op.drop_column('organizations', 'payfast_subscription_token')
    # ### end Alembic commands ###
