"""Add meal break fields to Shift model for BCEA compliance

Revision ID: 110e433d0604
Revises: 12ec71993a86
Create Date: 2025-11-04 13:47:25.137028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110e433d0604'
down_revision = '12ec71993a86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('includes_meal_break', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('meal_break_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'meal_break_duration_minutes')
    op.drop_column('shifts', 'includes_meal_break')
    # ### end Alembic commands ###
