"""Add Roster and ShiftAssignment models

Revision ID: 12ec71993a86
Revises: 862c9ee16cef
Create Date: 2025-11-04 13:46:18.166437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ec71993a86'
down_revision = '862c9ee16cef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosters',
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('roster_code', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('optimization_started_at', sa.DateTime(), nullable=True),
    sa.Column('optimization_completed_at', sa.DateTime(), nullable=True),
    sa.Column('optimization_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_shifts', sa.Integer(), nullable=False),
    sa.Column('assigned_shifts', sa.Integer(), nullable=False),
    sa.Column('unassigned_shifts', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('regular_pay_cost', sa.Float(), nullable=False),
    sa.Column('overtime_cost', sa.Float(), nullable=False),
    sa.Column('premium_cost', sa.Float(), nullable=False),
    sa.Column('travel_reimbursement', sa.Float(), nullable=False),
    sa.Column('bcea_compliant', sa.Boolean(), nullable=False),
    sa.Column('psira_compliant', sa.Boolean(), nullable=False),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('solver_objective_value', sa.Float(), nullable=True),
    sa.Column('solver_log', sa.Text(), nullable=True),
    sa.Column('algorithm_used', sa.String(length=50), nullable=True),
    sa.Column('fairness_score', sa.Float(), nullable=True),
    sa.Column('max_hours_employee', sa.Float(), nullable=True),
    sa.Column('min_hours_employee', sa.Float(), nullable=True),
    sa.Column('hours_std_dev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('roster_id')
    )
    op.create_index(op.f('ix_rosters_roster_code'), 'rosters', ['roster_code'], unique=True)
    op.create_index(op.f('ix_rosters_roster_id'), 'rosters', ['roster_id'], unique=False)
    op.create_index(op.f('ix_rosters_status'), 'rosters', ['status'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('regular_pay', sa.Float(), nullable=False),
    sa.Column('overtime_pay', sa.Float(), nullable=False),
    sa.Column('night_premium', sa.Float(), nullable=False),
    sa.Column('weekend_premium', sa.Float(), nullable=False),
    sa.Column('travel_reimbursement', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_datetime', sa.DateTime(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('checked_out', sa.Boolean(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.roster_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_shift_assignments_assignment_id'), 'shift_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_roster_id'), 'shift_assignments', ['roster_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_shift_id'), 'shift_assignments', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_assignments_shift_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_roster_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_assignment_id'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_rosters_status'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_roster_id'), table_name='rosters')
    op.drop_index(op.f('ix_rosters_roster_code'), table_name='rosters')
    op.drop_table('rosters')
    # ### end Alembic commands ###
