"""add_gender_field_to_employees

Revision ID: 1af9fd120774
Revises: 68edf8c1ee2d
Create Date: 2025-11-18 09:35:07.606800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1af9fd120774'
down_revision = '68edf8c1ee2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create gender enum type first
    gender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)

    # Add gender column to employees
    op.add_column('employees', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_assignments', 'roster_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('employees', sa.Column('hired_from_marketplace', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('average_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('total_ratings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('marketplace_applicant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_marketplace_applicant_id_fkey', 'employees', 'guard_applicants', ['marketplace_applicant_id'], ['applicant_id'], ondelete='SET NULL')
    op.alter_column('employees', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('employees', 'gender')
    op.create_table('guard_ratings',
    sa.Column('rating_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('punctuality_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('professionalism_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('competence_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reliability_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('areas_for_improvement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('would_rehire', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='guard_ratings_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], name='guard_ratings_job_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rated_by'], ['employees.employee_id'], name='guard_ratings_rated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('rating_id', name='guard_ratings_pkey')
    )
    op.create_index('ix_guard_ratings_rating_id', 'guard_ratings', ['rating_id'], unique=False)
    op.create_index('ix_guard_ratings_employee_id', 'guard_ratings', ['employee_id'], unique=False)
    op.create_table('ab_tests',
    sa.Column('test_id', sa.INTEGER(), server_default=sa.text("nextval('ab_tests_test_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('variant_a_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('variant_b_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('variant_a_conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_a_exposures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_b_conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('variant_b_exposures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winner', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_id', name='ab_tests_pkey'),
    sa.UniqueConstraint('test_name', name='ab_tests_test_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('job_postings',
    sa.Column('job_id', sa.INTEGER(), server_default=sa.text("nextval('job_postings_job_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('required_psira_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('required_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('required_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remote_possible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('shift_pattern', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_min', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('salary_max', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('positions_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contract_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contract_duration_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requires_drivers_license', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('requires_firearm_competency', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('filled_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='job_postings_client_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name='job_postings_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], name='job_postings_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='job_postings_site_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id', name='job_postings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_job_postings_status', 'job_postings', ['status'], unique=False)
    op.create_index('ix_job_postings_province', 'job_postings', ['province'], unique=False)
    op.create_index('ix_job_postings_job_id', 'job_postings', ['job_id'], unique=False)
    op.create_table('rules_config',
    sa.Column('rule_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('value_string', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name='rules_config_pkey'),
    sa.UniqueConstraint('rule_name', name='rules_config_rule_name_key')
    )
    op.create_index('ix_rules_config_rule_id', 'rules_config', ['rule_id'], unique=False)
    op.create_table('attendance',
    sa.Column('attend_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clock_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('variance_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='attendance_employee_id_fkey'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], name='attendance_shift_id_fkey'),
    sa.PrimaryKeyConstraint('attend_id', name='attendance_pkey')
    )
    op.create_index('ix_attendance_shift_id', 'attendance', ['shift_id'], unique=True)
    op.create_index('ix_attendance_employee_id', 'attendance', ['employee_id'], unique=False)
    op.create_index('ix_attendance_attend_id', 'attendance', ['attend_id'], unique=False)
    op.create_table('marketplace_commissions',
    sa.Column('commission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commission_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'ZAR'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deduction_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('installments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installments_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_per_installment', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('next_deduction_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.application_id'], name='marketplace_commissions_application_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='marketplace_commissions_employee_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], name='marketplace_commissions_job_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], name='marketplace_commissions_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('commission_id', name='marketplace_commissions_pkey')
    )
    op.create_index('ix_marketplace_commissions_organization_id', 'marketplace_commissions', ['organization_id'], unique=False)
    op.create_index('ix_marketplace_commissions_commission_type', 'marketplace_commissions', ['commission_type'], unique=False)
    op.create_index('ix_marketplace_commissions_commission_id', 'marketplace_commissions', ['commission_id'], unique=False)
    op.create_table('guard_applicants',
    sa.Column('applicant_id', sa.INTEGER(), server_default=sa.text("nextval('guard_applicants_applicant_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('psira_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('psira_grade', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('psira_expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('psira_certificate_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('suburb', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('provinces_willing_to_work', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('available_for_work', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hourly_rate_expectation', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('has_drivers_license', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('drivers_license_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('has_firearm_competency', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('firearm_competency_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cv_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('profile_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending_verification'::character varying"), autoincrement=False, nullable=False),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_generated_cv', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cv_purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_purchase_id'], ['cv_purchases.purchase_id'], name='guard_applicants_cv_purchase_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], name='guard_applicants_verified_by_fkey'),
    sa.PrimaryKeyConstraint('applicant_id', name='guard_applicants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_guard_applicants_psira_number', 'guard_applicants', ['psira_number'], unique=True)
    op.create_index('ix_guard_applicants_email', 'guard_applicants', ['email'], unique=True)
    op.create_index('ix_guard_applicants_applicant_id', 'guard_applicants', ['applicant_id'], unique=False)
    op.create_table('generated_cvs',
    sa.Column('cv_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cv_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_downloaded', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['guard_applicants.applicant_id'], name='generated_cvs_applicant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['cv_purchases.purchase_id'], name='generated_cvs_purchase_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cv_id', name='generated_cvs_pkey')
    )
    op.create_index('ix_generated_cvs_template_name', 'generated_cvs', ['template_name'], unique=False)
    op.create_index('ix_generated_cvs_cv_id', 'generated_cvs', ['cv_id'], unique=False)
    op.create_index('ix_generated_cvs_applicant_id', 'generated_cvs', ['applicant_id'], unique=False)
    op.create_table('skills_matrix',
    sa.Column('skill_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('certified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cert_expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='skills_matrix_employee_id_fkey'),
    sa.PrimaryKeyConstraint('skill_id', name='skills_matrix_pkey')
    )
    op.create_index('ix_skills_matrix_skill_id', 'skills_matrix', ['skill_id'], unique=False)
    op.create_index('ix_skills_matrix_employee_id', 'skills_matrix', ['employee_id'], unique=False)
    op.create_table('analytics_daily_metrics',
    sa.Column('metric_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rosters_generated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shifts_created', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employees_added', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_roster_fill_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_optimization_time_seconds', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('compliance_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cost_scheduled', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_cost_per_shift', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('sessions_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_session_duration_minutes', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('features_used_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='analytics_daily_metrics_org_id_fkey'),
    sa.PrimaryKeyConstraint('metric_id', name='analytics_daily_metrics_pkey')
    )
    op.create_index('idx_org_date', 'analytics_daily_metrics', ['org_id', 'date'], unique=True)
    op.create_table('incident_reports',
    sa.Column('incident_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('incident_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reported_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('incident_type', postgresql.ENUM('THEFT', 'BURGLARY', 'ASSAULT', 'TRESPASSING', 'VANDALISM', 'SUSPICIOUS_ACTIVITY', 'FIRE', 'MEDICAL_EMERGENCY', 'EQUIPMENT_FAILURE', 'ACCESS_CONTROL_BREACH', 'VEHICLE_INCIDENT', 'ARMED_ROBBERY', 'PROTEST_UNREST', 'BOMB_THREAT', 'OTHER', name='incidenttype'), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), autoincrement=False, nullable=False),
    sa.Column('incident_category', postgresql.ENUM('CRIME', 'SAFETY', 'OPERATIONAL', 'CLIENT_PROPERTY', 'ENVIRONMENTAL', 'PERSONNEL', name='incidentcategory'), autoincrement=False, nullable=True),
    sa.Column('location_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exact_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suspect_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('victim_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('witness_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('police_notified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('police_case_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('police_station', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('client_notified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('client_notified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('injuries_reported', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('medical_attention_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ambulance_called', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('property_damage', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('property_damage_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_loss_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('evidence_collected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('evidence_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photos_attached', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('document_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('supervisor_reviewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('supervisor_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('follow_up_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('follow_up_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'UNDER_INVESTIGATION', 'RESOLVED', 'CLOSED', name='incidentstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='incident_reports_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='incident_reports_site_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.employee_id'], name='incident_reports_supervisor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('incident_id', name='incident_reports_pkey')
    )
    op.create_index('ix_incident_reports_status', 'incident_reports', ['status'], unique=False)
    op.create_index('ix_incident_reports_site_id', 'incident_reports', ['site_id'], unique=False)
    op.create_index('ix_incident_reports_incident_type', 'incident_reports', ['incident_type'], unique=False)
    op.create_index('ix_incident_reports_incident_id', 'incident_reports', ['incident_id'], unique=False)
    op.create_index('ix_incident_reports_incident_date', 'incident_reports', ['incident_date'], unique=False)
    op.create_index('ix_incident_reports_employee_id', 'incident_reports', ['employee_id'], unique=False)
    op.create_table('ob_entries',
    sa.Column('entry_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('VISITOR', 'KEY_HANDOVER', 'ALARM', 'PATROL', 'EQUIPMENT', 'OBSERVATION', 'HANDOVER', 'OTHER', name='obcategory'), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entry_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('photo_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location_accuracy', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_reviewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('supervisor_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('requires_review', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='ob_entries_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], name='ob_entries_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], name='ob_entries_shift_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='ob_entries_site_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.employee_id'], name='ob_entries_supervisor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entry_id', name='ob_entries_pkey')
    )
    op.create_index('ix_ob_entries_timestamp', 'ob_entries', ['timestamp'], unique=False)
    op.create_index('ix_ob_entries_site_id', 'ob_entries', ['site_id'], unique=False)
    op.create_index('ix_ob_entries_organization_id', 'ob_entries', ['organization_id'], unique=False)
    op.create_index('ix_ob_entries_entry_id', 'ob_entries', ['entry_id'], unique=False)
    op.create_index('ix_ob_entries_employee_id', 'ob_entries', ['employee_id'], unique=False)
    op.create_index('ix_ob_entries_category', 'ob_entries', ['category'], unique=False)
    op.create_table('shift_groups',
    sa.Column('shift_group_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('group_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('required_guards', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('required_supervisors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='shiftgroupstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='shift_groups_site_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.org_id'], name='shift_groups_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_group_id', name='shift_groups_pkey')
    )
    op.create_index('ix_shift_groups_tenant_id', 'shift_groups', ['tenant_id'], unique=False)
    op.create_index('ix_shift_groups_status', 'shift_groups', ['status'], unique=False)
    op.create_index('ix_shift_groups_start_time', 'shift_groups', ['start_time'], unique=False)
    op.create_index('ix_shift_groups_site_id', 'shift_groups', ['site_id'], unique=False)
    op.create_index('ix_shift_groups_shift_group_id', 'shift_groups', ['shift_group_id'], unique=False)
    op.create_table('feature_usage_stats',
    sa.Column('stat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unique_users_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('avg_uses_per_week', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='feature_usage_stats_org_id_fkey'),
    sa.PrimaryKeyConstraint('stat_id', name='feature_usage_stats_pkey')
    )
    op.create_index('idx_org_feature', 'feature_usage_stats', ['org_id', 'feature_name'], unique=True)
    op.create_table('daily_occurrence_books',
    sa.Column('ob_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ob_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('shift_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('weather_conditions', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('site_conditions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patrol_rounds_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('patrol_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('visitors_logged', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visitor_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('equipment_checked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('equipment_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equipment_issues', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incidents_reported', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('incident_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unusual_activities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('handover_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relieving_officer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relieving_officer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('handover_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('keys_handed_over', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('keys_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('supervisor_reviewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('supervisor_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='daily_occurrence_books_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relieving_officer_id'], ['employees.employee_id'], name='daily_occurrence_books_relieving_officer_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], name='daily_occurrence_books_shift_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='daily_occurrence_books_site_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.employee_id'], name='daily_occurrence_books_supervisor_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ob_id', name='daily_occurrence_books_pkey')
    )
    op.create_index('ix_daily_occurrence_books_site_id', 'daily_occurrence_books', ['site_id'], unique=False)
    op.create_index('ix_daily_occurrence_books_ob_id', 'daily_occurrence_books', ['ob_id'], unique=False)
    op.create_index('ix_daily_occurrence_books_ob_date', 'daily_occurrence_books', ['ob_date'], unique=False)
    op.create_index('ix_daily_occurrence_books_employee_id', 'daily_occurrence_books', ['employee_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('page_load_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='analytics_events_org_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='analytics_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='analytics_events_pkey')
    )
    op.create_index('ix_analytics_events_timestamp', 'analytics_events', ['timestamp'], unique=False)
    op.create_index('ix_analytics_events_event_name', 'analytics_events', ['event_name'], unique=False)
    op.create_index('idx_user_timestamp', 'analytics_events', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_org_timestamp', 'analytics_events', ['org_id', 'timestamp'], unique=False)
    op.create_index('idx_event_name_timestamp', 'analytics_events', ['event_name', 'timestamp'], unique=False)
    op.create_table('bulk_hiring_packages',
    sa.Column('package_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hires_quota', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hires_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], name='bulk_hiring_packages_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('package_id', name='bulk_hiring_packages_pkey')
    )
    op.create_index('ix_bulk_hiring_packages_package_type', 'bulk_hiring_packages', ['package_type'], unique=False)
    op.create_index('ix_bulk_hiring_packages_package_id', 'bulk_hiring_packages', ['package_id'], unique=False)
    op.create_index('ix_bulk_hiring_packages_organization_id', 'bulk_hiring_packages', ['organization_id'], unique=False)
    op.create_table('customer_health_scores',
    sa.Column('score_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('health_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('usage_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('adoption_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('satisfaction_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('growth_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('churn_risk', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], name='customer_health_scores_org_id_fkey'),
    sa.PrimaryKeyConstraint('score_id', name='customer_health_scores_pkey')
    )
    op.create_index('idx_org_health', 'customer_health_scores', ['org_id', 'calculated_at'], unique=False)
    op.create_index('idx_health_status', 'customer_health_scores', ['health_status'], unique=False)
    op.create_index('idx_churn_risk', 'customer_health_scores', ['churn_risk'], unique=False)
    op.create_table('ab_test_assignments',
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('converted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['ab_tests.test_id'], name='ab_test_assignments_test_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='ab_test_assignments_user_id_fkey'),
    sa.PrimaryKeyConstraint('assignment_id', name='ab_test_assignments_pkey')
    )
    op.create_index('idx_test_user', 'ab_test_assignments', ['test_id', 'user_id'], unique=True)
    op.create_table('job_applications',
    sa.Column('application_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'submitted'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interview_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interview_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('hired_as_employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['guard_applicants.applicant_id'], name='job_applications_applicant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hired_as_employee_id'], ['employees.employee_id'], name='job_applications_hired_as_employee_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], name='job_applications_job_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], name='job_applications_reviewed_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('application_id', name='job_applications_pkey')
    )
    op.create_index('ix_job_applications_status', 'job_applications', ['status'], unique=False)
    op.create_index('ix_job_applications_job_id', 'job_applications', ['job_id'], unique=False)
    op.create_index('ix_job_applications_application_id', 'job_applications', ['application_id'], unique=False)
    op.create_index('ix_job_applications_applicant_id', 'job_applications', ['applicant_id'], unique=False)
    op.create_table('premium_job_postings',
    sa.Column('premium_job_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('priority_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badge_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('boost_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('auto_renew', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applications_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], name='premium_job_postings_job_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], name='premium_job_postings_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('premium_job_id', name='premium_job_postings_pkey')
    )
    op.create_index('ix_premium_job_postings_premium_job_id', 'premium_job_postings', ['premium_job_id'], unique=False)
    op.create_index('ix_premium_job_postings_organization_id', 'premium_job_postings', ['organization_id'], unique=False)
    op.create_index('ix_premium_job_postings_job_id', 'premium_job_postings', ['job_id'], unique=True)
    op.create_table('expenses',
    sa.Column('expense_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('FUEL', 'MEAL', 'ALLOWANCE', 'UNIFORM', 'VEHICLE', 'OTHER', name='expensetype'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date_incurred', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='expenses_employee_id_fkey'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='expenses_site_id_fkey'),
    sa.PrimaryKeyConstraint('expense_id', name='expenses_pkey')
    )
    op.create_index('ix_expenses_site_id', 'expenses', ['site_id'], unique=False)
    op.create_index('ix_expenses_expense_id', 'expenses', ['expense_id'], unique=False)
    op.create_index('ix_expenses_employee_id', 'expenses', ['employee_id'], unique=False)
    op.create_index('ix_expenses_date_incurred', 'expenses', ['date_incurred'], unique=False)
    op.create_table('cv_purchases',
    sa.Column('purchase_id', sa.INTEGER(), server_default=sa.text("nextval('cv_purchases_purchase_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('60.00'), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['guard_applicants.applicant_id'], name='cv_purchases_applicant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_id', name='cv_purchases_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_cv_purchases_purchase_id', 'cv_purchases', ['purchase_id'], unique=False)
    op.create_index('ix_cv_purchases_applicant_id', 'cv_purchases', ['applicant_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('leave_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('leave_type', postgresql.ENUM('ANNUAL', 'SICK', 'FAMILY_RESPONSIBILITY', 'UNPAID', 'STUDY', 'MATERNITY', 'PATERNITY', 'OTHER', name='leavetype'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], name='leave_requests_approved_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='leave_requests_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leave_id', name='leave_requests_pkey')
    )
    op.create_index('ix_leave_requests_status', 'leave_requests', ['status'], unique=False)
    op.create_index('ix_leave_requests_start_date', 'leave_requests', ['start_date'], unique=False)
    op.create_index('ix_leave_requests_leave_id', 'leave_requests', ['leave_id'], unique=False)
    op.create_index('ix_leave_requests_employee_id', 'leave_requests', ['employee_id'], unique=False)
    # ### end Alembic commands ###
