"""Add all tables including users

Revision ID: 262aadcf58ff
Revises: 
Create Date: 2025-10-31 08:31:26.616620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262aadcf58ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ARMED', 'UNARMED', 'SUPERVISOR', name='employeerole'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('max_hours_week', sa.Integer(), nullable=True),
    sa.Column('cert_level', sa.String(length=50), nullable=True),
    sa.Column('home_location', sa.String(length=200), nullable=True),
    sa.Column('home_gps_lat', sa.Float(), nullable=True),
    sa.Column('home_gps_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_id_number'), 'employees', ['id_number'], unique=True)
    op.create_table('rules_config',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_string', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_rules_config_rule_id'), 'rules_config', ['rule_id'], unique=False)
    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('shift_pattern', sa.String(length=50), nullable=True),
    sa.Column('required_skill', sa.String(length=100), nullable=True),
    sa.Column('billing_rate', sa.Float(), nullable=True),
    sa.Column('min_staff', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_index(op.f('ix_sites_site_id'), 'sites', ['site_id'], unique=False)
    op.create_table('availability',
    sa.Column('avail_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('avail_id')
    )
    op.create_index(op.f('ix_availability_avail_id'), 'availability', ['avail_id'], unique=False)
    op.create_index(op.f('ix_availability_date'), 'availability', ['date'], unique=False)
    op.create_index(op.f('ix_availability_employee_id'), 'availability', ['employee_id'], unique=False)
    op.create_table('certifications',
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('cert_type', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('cert_number', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('cert_id')
    )
    op.create_index(op.f('ix_certifications_cert_id'), 'certifications', ['cert_id'], unique=False)
    op.create_index(op.f('ix_certifications_employee_id'), 'certifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_certifications_expiry_date'), 'certifications', ['expiry_date'], unique=False)
    op.create_table('expenses',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('FUEL', 'MEAL', 'ALLOWANCE', 'UNIFORM', 'VEHICLE', 'OTHER', name='expensetype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_incurred', sa.Date(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_index(op.f('ix_expenses_date_incurred'), 'expenses', ['date_incurred'], unique=False)
    op.create_index(op.f('ix_expenses_employee_id'), 'expenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expenses_site_id'), 'expenses', ['site_id'], unique=False)
    op.create_table('payroll_summary',
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('gross_pay', sa.Float(), nullable=True),
    sa.Column('expenses_total', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('payroll_id')
    )
    op.create_index(op.f('ix_payroll_summary_employee_id'), 'payroll_summary', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_summary_payroll_id'), 'payroll_summary', ['payroll_id'], unique=False)
    op.create_index(op.f('ix_payroll_summary_period_start'), 'payroll_summary', ['period_start'], unique=False)
    op.create_table('shift_templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=True),
    sa.Column('required_staff_count', sa.Integer(), nullable=True),
    sa.Column('pattern_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_shift_templates_site_id'), 'shift_templates', ['site_id'], unique=False)
    op.create_index(op.f('ix_shift_templates_template_id'), 'shift_templates', ['template_id'], unique=False)
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('required_skill', sa.String(length=100), nullable=True),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='shiftstatus'), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shifts_assigned_employee_id'), 'shifts', ['assigned_employee_id'], unique=False)
    op.create_index(op.f('ix_shifts_shift_id'), 'shifts', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shifts_site_id'), 'shifts', ['site_id'], unique=False)
    op.create_index(op.f('ix_shifts_start_time'), 'shifts', ['start_time'], unique=False)
    op.create_table('skills_matrix',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=True),
    sa.Column('cert_expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_matrix_employee_id'), 'skills_matrix', ['employee_id'], unique=False)
    op.create_index(op.f('ix_skills_matrix_skill_id'), 'skills_matrix', ['skill_id'], unique=False)
    op.create_table('attendance',
    sa.Column('attend_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('variance_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('attend_id')
    )
    op.create_index(op.f('ix_attendance_attend_id'), 'attendance', ['attend_id'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_shift_id'), 'attendance', ['shift_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_shift_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attend_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_skills_matrix_skill_id'), table_name='skills_matrix')
    op.drop_index(op.f('ix_skills_matrix_employee_id'), table_name='skills_matrix')
    op.drop_table('skills_matrix')
    op.drop_index(op.f('ix_shifts_start_time'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_site_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_shift_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_assigned_employee_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_shift_templates_template_id'), table_name='shift_templates')
    op.drop_index(op.f('ix_shift_templates_site_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_index(op.f('ix_payroll_summary_period_start'), table_name='payroll_summary')
    op.drop_index(op.f('ix_payroll_summary_payroll_id'), table_name='payroll_summary')
    op.drop_index(op.f('ix_payroll_summary_employee_id'), table_name='payroll_summary')
    op.drop_table('payroll_summary')
    op.drop_index(op.f('ix_expenses_site_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_employee_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date_incurred'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_certifications_expiry_date'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_employee_id'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_cert_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_availability_employee_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_date'), table_name='availability')
    op.drop_index(op.f('ix_availability_avail_id'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_sites_site_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_rules_config_rule_id'), table_name='rules_config')
    op.drop_table('rules_config')
    op.drop_index(op.f('ix_employees_id_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
