"""add_trial_dates_to_organization

Revision ID: 9d0a5af72ce3
Revises: fcb825be69c0
Create Date: 2025-11-12 13:47:26.714290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0a5af72ce3'
down_revision = 'fcb825be69c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trial_start_date', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('trial_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_end_date')
    op.drop_column('organizations', 'trial_start_date')
    # ### end Alembic commands ###
