"""add_ob_entry_model

Revision ID: f9e708f7c990
Revises: 9d0a5af72ce3
Create Date: 2025-11-12 13:52:42.160560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e708f7c990'
down_revision = '9d0a5af72ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ob_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('VISITOR', 'KEY_HANDOVER', 'ALARM', 'PATROL', 'EQUIPMENT', 'OBSERVATION', 'HANDOVER', 'OTHER', name='obcategory'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entry_data', sa.JSON(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('location_accuracy', sa.String(length=50), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_reviewed', sa.Boolean(), nullable=False),
    sa.Column('supervisor_comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_index(op.f('ix_ob_entries_category'), 'ob_entries', ['category'], unique=False)
    op.create_index(op.f('ix_ob_entries_employee_id'), 'ob_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_ob_entries_entry_id'), 'ob_entries', ['entry_id'], unique=False)
    op.create_index(op.f('ix_ob_entries_organization_id'), 'ob_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ob_entries_site_id'), 'ob_entries', ['site_id'], unique=False)
    op.create_index(op.f('ix_ob_entries_timestamp'), 'ob_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ob_entries_timestamp'), table_name='ob_entries')
    op.drop_index(op.f('ix_ob_entries_site_id'), table_name='ob_entries')
    op.drop_index(op.f('ix_ob_entries_organization_id'), table_name='ob_entries')
    op.drop_index(op.f('ix_ob_entries_entry_id'), table_name='ob_entries')
    op.drop_index(op.f('ix_ob_entries_employee_id'), table_name='ob_entries')
    op.drop_index(op.f('ix_ob_entries_category'), table_name='ob_entries')
    op.drop_table('ob_entries')
    # ### end Alembic commands ###
